### ISSUE TITLE
Limit on number of content types which can be exposed

### ISSUE THREAD

**Issue by pmasonids** [oriel-hub/WordPress-Expose#2]
There appears to be a limit to the number of content types with large numbers of fields. Although the settings are saved in the admin interface, on returning to the page not all the options are selected.

**Comment by pmasonids** [comment]
This may be related to this issue: https://vip.wordpress.com/documentation/best-practices/options-cache/

**Comment by accuosto** [comment]
The number of exposed fields are limited by the PHP variable max_input_vars, which should be increased if a large number of fields in a large number of content types are selected.
